"""
ExecutorAgent — Agent C of the three-agent pipeline.

Takes the best_model dict from AutoResearchWrapper and:
1. Generates a new .ipynb notebook using nbformat with optimised params pre-filled
2. Stores it as a new ledger entry via MCPServer
3. Logs completion trace

Usage:
    executor = ExecutorAgent(rag=rag, llm=llm, db=db)
    result = executor.execute(
        best_model={"name": "LGBMClassifier", "params": {...}, "metrics": {...}},
        source_file="notebooks/exp1.ipynb",
        run_id="a1b2c3d4",
        goal="Improve F1 score",
    )
"""

import uuid
from pathlib import Path
from typing import Dict, Optional

import nbformat as nbf

from .base_agent import BaseAgent


class ExecutorAgent(BaseAgent):
    def __init__(self, rag_system=None, llm=None, db=None):
        super().__init__(rag_system, llm)
        self.db = db

    def suggest(self, context: Dict) -> Dict:
        """BaseAgent interface — delegates to execute()."""
        return self.execute(
            best_model=context.get("best_model", {}),
            source_file=context.get("source_file", ""),
            run_id=context.get("run_id"),
            goal=context.get("goal", ""),
        )

    def execute(
        self,
        best_model: Dict,
        source_file: str = "",
        run_id: Optional[str] = None,
        goal: str = "",
    ) -> Dict:
        """
        Generate an optimised notebook and register it in the ledger.

        Returns:
            {status, notebook_path, entry_id, run_id}
        """
        run_id = run_id or uuid.uuid4().hex[:8]
        stem = Path(source_file).stem if source_file else "experiment"
        out_name = f"{stem}_optimised_{run_id[:6]}.ipynb"

        if self.db:
            self.db.log_trace(
                run_id, "executor",
                f"Generating optimised notebook from {Path(source_file).name if source_file else 'experiment'}...",
            )

        # ── Build notebook ─────────────────────────────────────────────────────
        nb = nbf.v4.new_notebook()
        nb.cells = [
            nbf.v4.new_markdown_cell(
                f"# Optimised Experiment — {best_model.get('name', 'Model')}\n"
                f"*Generated by Agentic DS Ledger — Executor Agent*\n\n"
                f"**Goal:** {goal or 'Improve model performance'}  \n"
                f"**Run ID:** `{run_id}`  \n"
                f"**Source:** `{source_file or 'unknown'}`"
            ),
            nbf.v4.new_markdown_cell("## Optimised Hyperparameters"),
            nbf.v4.new_code_cell(self._params_cell(best_model)),
            nbf.v4.new_markdown_cell(
                "## Train with Optimised Parameters\n\n"
                "> Replace `X_train`, `y_train` with your actual data before running."
            ),
            nbf.v4.new_code_cell(self._training_cell(best_model)),
        ]

        # ── Save notebook ──────────────────────────────────────────────────────
        try:
            nbf.write(nb, out_name)
        except Exception as e:
            if self.db:
                self.db.log_trace(run_id, "executor",
                    f"Failed to write notebook: {e}")
            return {"status": "error", "error": str(e), "run_id": run_id}

        # ── Store in ledger ────────────────────────────────────────────────────
        entry_id = None
        if self.db:
            try:
                from src.mcp_server import MCPServer
                mcp = MCPServer(db=self.db)
                metadata = {
                    "file_path": out_name,
                    "file_type": "ipynb",
                    "models": [best_model],
                    "metrics": [
                        {"name": k, "value": v}
                        for k, v in best_model.get("metrics", {}).items()
                        if isinstance(v, (int, float))
                    ],
                    "preprocessing": [],
                    "environment": {},
                    "raw_text": (
                        f"Optimised notebook for {best_model.get('name', 'model')}. "
                        f"Generated by Executor Agent (run_id={run_id})."
                    ),
                }
                entry_id = mcp.store_in_db(metadata)
            except Exception:
                pass

            self.db.log_trace(
                run_id, "executor",
                f"Notebook saved: {out_name}"
                + (f" | Ledger entry #{entry_id}" if entry_id else ""),
                payload={"notebook": out_name, "entry_id": entry_id},
                entry_id=entry_id,
            )

        return {
            "status": "ok",
            "notebook_path": out_name,
            "entry_id": entry_id,
            "run_id": run_id,
        }

    # ── Notebook cell builders ─────────────────────────────────────────────────

    def _params_cell(self, best_model: Dict) -> str:
        params = best_model.get("params", {})
        lines = [
            f"# ── Optimised hyperparameters ──────────────────────────────────",
            f"# Model: {best_model.get('name', 'Unknown')} ({best_model.get('family', '')})",
            "",
        ]
        for k, v in params.items():
            val = f'"{v}"' if isinstance(v, str) else ("None" if v is None else str(v))
            lines.append(f"{k} = {val}")
        lines += ["", "# Best metrics achieved on stratified sample:"]
        for k, v in best_model.get("metrics", {}).items():
            if isinstance(v, (int, float)):
                lines.append(f"# {k}: {v:.4f}")
        return "\n".join(lines)

    def _training_cell(self, best_model: Dict) -> str:
        name = best_model.get("name", "YourModel")
        params = best_model.get("params", {})
        param_str = ", ".join(
            f"{k}={k}" for k in params if params[k] is not None
        )
        return (
            f"from sklearn.model_selection import cross_val_score\n"
            f"# from sklearn.ensemble import {name}  # uncomment as needed\n\n"
            f"model = {name}({param_str})\n"
            f"scores = cross_val_score(\n"
            f"    model, X_train, y_train,\n"
            f"    cv=5, scoring='f1_weighted', n_jobs=-1,\n"
            f")\n"
            f"print(f'CV F1: {{scores.mean():.4f}} ± {{scores.std():.4f}}')\n\n"
            f"model.fit(X_train, y_train)\n"
            f"print('Training complete.')"
        )
